maven_plugin/pom.xml
I noticed that Maven Lockfile depends on an older version of Instancio. I updated the version to the latest `instancio-junit` artifact (since Maven Lockfile uses JUnit Jupiter).
=> 📌 Update instancio version to 2.12.1

github_action/src/main/java/io/github/chains_project/maven_lockfile/GithubAction.java
This commit adds a new version field to GithubAction class and configures the injection of extension version from the pom.xml. The field's access level is set to package-private to avoid excessive reflection usage. This will make it possible for the class to read the version of the extension and will allow for more efficient reflection usage.
=> ♻️  Add version field and configure injection of extension version in GithubAction class

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/graph/DependencyGraph.java
To avoid potential null pointer exceptions, this refactor includes a check in the DependencyGraph constructor to handle null input. The constructor will now initialize an empty list when passed a null value.
=> ♻️ Refactor DependencyGraph constructor to handle null input

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/ValidateChecksumMojo.java
The unnecessary Javadoc comment for a private field has been removed from ValidateChecksumMojo.
=> ♻️  Remove redundant code comments in ValidateChecksumMojo

renovate.json
Change the automerge strategy in renovate.json to "squash" for cleaner commit logs.
=> 🔼 Update renovate.json with squash strategy

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/data/LockFile.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/graph/NodeId.java
This commit updates LockFile.java to add a check to see if the passed-in dependency and plugin lists are null before setting them. If they are, return an empty list instead. NodeId.java also declares groupId, artifactId, and version variables as final.
=> ✨ Add null checks for dependencies & mavenPlugins

README.md, maven_plugin/lockfile.json, maven_plugin/pom.xml, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/GenerateLockFileMojo.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/LockFileFacade.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/ValidateChecksumMojo.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/data/LockFile.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/data/Metadata.java
In every lockfile we now record the maven, java and os version of the environment. Also we print a warning if this does not match the original one.
Integration tests for this feature are missing.
fixes #203
=> feat: ✨ Add metadata to lockfile

lockfile.json, maven_plugin/lockfile.json, maven_plugin/pom.xml
A new Maven plugin is included in pom.xml to validate dependencies and prevent conflicts. The maven-lockfile plugin is configured to include all Maven plugins and performs a validation goal during the build process.
=> ✨ Added maven-lockfile plugin for better dependency management

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/ValidateChecksumMojo.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/data/LockFile.java
The lock file validation failed due to differences found. The error message now displays the missing dependencies and details about the lock-files version differences.
=> 🐛 Update lockfile validation error message

maven_plugin/pom.xml
The <io.github.chains-project.maven-lockfile> plugin was removed from the Maven build process as it was deemed redundant. It no longer participated in the plugin's execution stages.
=> ✨ Removed redundant Maven plugin from pom.xml

action.yml, github_action/pom.xml, jreleaser.yml, lockfile.json, maven_plugin/lockfile.json, maven_plugin/pom.xml, pom.xml
The version of `maven-lockfile-parent`, `maven-lockfile-github-action`, `maven-lockfile`, and the root pom are changed from `3.3.1-SNAPSHOT` to `3.4.1-SNAPSHOT`. Additionally, metadata such as the `description` and `url` are added to `maven-lockfile-github-action` and `maven-lockfile`. Finally, `maven-lockfile` is further improved with a new `description` that explains how it guards against malicious actors.
=> 📝 Update lockfile versions & add metadata

qodana.yml
Included dependency license checker and enabled an inspection group for selected paths while disabling an excluded inspection group.
=> 🔍 Add dependency license checker to Qodana

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/FreezeDependencyMojo.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/graph/DependencyGraph.java, maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/graph/DependencyNode.java
Fixes 
- https://github.com/chains-project/maven-lockfile/issues/687
- https://github.com/chains-project/maven-lockfile/issues/686
- https://github.com/chains-project/maven-lockfile/issues/683
- Adds a new field "included" to the lockfile to track the dependency conflict resolution.
=> 🐛 Update the dependency resolution mechanism and fix duplicates in freeze

README.md, action.yml, template/action.yml
The github action would only trigger when the pom.xml was changed. If someone makes a PR where the lockfile.json is changed but the pom stays the same. The maven-lockfile github action would not trigger and a faulty lockfile might accidentally get commited. Someone could for example modify a checksum thus enabeling tampered dependencies to pass a verify check later.
Se #881
=> :construction_worker: feat: trigger github action on changed lockfile.json

.github/workflows/jreleaser.yml
This will allow the release action to complete without requiring manual ff-merge. It looks as if the cyclone.json is staged in the SNAPSHOT and will test if/why it is not included in the final release if the newer maven version does not fix it.
=> 🛠️ use maven 3.9.6 and wait for checks before ff merge in release

.github/workflows/jreleaser.yml
Triggers error when trying to release as main branch is protected. Lockfile is guaranteed to be updated by CI.
=> 🛠️ Do not push lockfile as part of release

.github/workflows/LockfilePR.yml, README.md, action.yml, github_action/src/main/java/io/github/chains_project/maven_lockfile/GithubAction.java, template/action.yml
In case `commit-lockfile` is false it will verify the lockfile instead of commiting a new one. Previously if you set `commit-lockfile` and only wanted it to check the lockfile, in case the pom.xml had updated. It would create the new lockfile, not commit it, and then successfully finish the action.
It now allways runs the verify in case commit-lockfile is false, if commit-lockfile is true it will verify if pom is same and update/commit if pom has changed.
Added documentation in the README.md for the action parameters.
=> 👷 ci: Verify lockfile in case commit-lockfile is false

.github/workflows/jreleaser.yml
This is a temporary fix, I want to do the release using 5.2.4 which is not yet released. This way it will do the release but will not verify the lockfile (as it runs 5.2.0 and #880 is not implemented). We can then update to 5.2.4 which has #880 merged and will validate.
The pom.xml is updated, and we do know that lockfile.json is correct from the action running on the main branch.
=> 💚  fix ci: Do not try to commit lockfile to main branch in relesae

CHANGELOG.md, action.yml, github_action/lockfile.json, github_action/pom.xml, lockfile.json, maven_plugin/lockfile.json, maven_plugin/pom.xml, pom.xml
Release release/5.3.0 ff-merge
=> Release release/5.3.0 ff-merge

action.yml, template/action.yml
This has been a journey. Because of an update to quarkus the CI now requires Java 17 in the github aciton. Do note that the maven plugin is still compiled and works with Java 11.
Because the action needed to be updated a release was required before the new version could be used. Unfortunately some releases (e.g. 5.3.0) will not work in CI since quarkus was automatically updated and no CI test caught that it required Java 17, thus merging it and it went with the 5.3.0 release while it still used Java 11 in the action.yml.
=> 💚 fix ci: Fix erroneous indentation in action.yml

.github/workflows/jreleaser.yml, README.md, action.yml, template/action.yml
See #1042.
The project itself currently runs maven-lockfile directly using `jbang` in the relase action. Some more thought has to be put into if/how the maven-lockfile/action.yml should/could be used instead. It would be more convenient as it automatically set up the environment needed with java, maven and jbang. But during the release action it must be able to be run on newly created (not yet pushed) branches, on updated pom.xml's that are not commited, etc.
=> 📝 👷 docs: ci: Document and update syncronizing lockfile with release

.github/workflows/Lockfile.yml, .github/workflows/LockfilePR.yml, .github/workflows/jreleaser.yml, .github/workflows/regenerate-lockfile.yml, action.yml, template/action.yml
5.4.1 will have to be used, see #1085 . Changed-files has been allowlisted.
=> 👷 ci: Use version 5.4.0 with removed non-allowlisted github actions

.github/workflows/Lockfile.yml, .github/workflows/LockfilePR.yml, .github/workflows/jreleaser.yml, .github/workflows/regenerate-lockfile.yml, action.yml, template/action.yml
After #1129, a new release with a working action has been created. This resets from the interim commit with the working action to a release.
=> 👷 ci: Reset action to current version and use release 5.4.2

renovate.json
We remove renovate updates for digest as we saw in #1111 that a malicious commit can be pointed by latest tag. However, we are still prone to attack if attacker releases the malicious commit with a new tag.
=> :broom: chore: remove digest updates as tags are mutable

.github/workflows/publish-action-artifact.yml, .mvn/maven.config
Some older maven versions and other tooling does not handle comments in maven.config.
=> 🚀 build: Remove comment in maven.config for older maven versions

.github/workflows/jreleaser.yml
Have to update to have environment secrets available.
=> 👷 ci: Run release action in environment release

renovate.json
See #1220. No longer needed with [ghasum](https://github.com/ericcornelissen/ghasum/).
=> 👷 ci: Remove pinDigest update from Renovate

.github/workflows/scorecard.yml
=> 👷 ci: Add repo.spring.io to allowlisted endpoints for ossf/scorecard

.github/workflows/scorecard.yml
=> 👷 ci: Reset ossf/scorecard to without ghasum to only include allowlisted steps

.github/workflows/ensure-release-notrunning.yml
=> 👷 ci: Pass ensure-release-action-is-not-running action if branch is "release/"

maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/GenerateLockFileMojo.java
See #1188.
As there is no distinction between user supplied value and default value we cannot have parameters override lockfile config, will keep current `-DgetConfigFromFile`.
=> ✨ feat: Update config when regenerating lockfile

.github/workflows/ensure-release-notrunning.yml
Fixes https://github.com/chains-project/maven-lockfile/security/code-scanning/355.
=> :lock: security: Remove github.head_ref from echo of ensure-release-action-is-not-running
