chains-project/maven-lockfile

- .github/workflows/jreleaser.yml
Jreleaser already handles tags
> 👷 Fix git tag pushing

- .github/workflows/jreleaser.yml
Related: https://github.com/nmasse-itix/demo-appdev/issues/1
> 🚑 Use java 11 instead of 17

- .github/workflows/jreleaser.yml
- jreleaser.yml
- pom.xml
Add JRELEASER_GITHUB_TOKEN environmental variable to actions/checkout to fetch repository. Change deployment directory to target/staging-deploy. Configuration for cyclonedx-maven-plugin is also updated to include test scope and set the output directory to staging-deploy.
> ✨ Add JRELEASER_GITHUB_TOKEN to actions/checkout, and change deployment directory

- .github/workflows/jreleaser.yml
- jreleaser.yml
- pom.xml
Add JRELEASER_GITHUB_TOKEN environmental variable to actions/checkout to fetch repository. Change deployment directory to target/staging-deploy. Configuration for cyclonedx-maven-plugin is also updated to include test scope and set the output directory to staging-deploy.
> 👷 Add JRELEASER_GITHUB_TOKEN environmental variable to actions/checkout to fetch repository

- README.md
- maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/AbstractLockfileMojo.java
- maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/ValidateChecksumMojo.java
- maven_plugin/src/main/java/io/github/chains_project/maven_lockfile/data/Config.java
- maven_plugin/src/test/java/io/github/chains_project/maven_lockfile/graph/LockfileTest.java
- maven_plugin/src/test/java/it/IntegrationTestsIT.java
- maven_plugin/src/test/resources-its/it/IntegrationTestsIT/singleDependencyCheckMustWarn/lockfile.json
- maven_plugin/src/test/resources-its/it/IntegrationTestsIT/singleDependencyCheckMustWarn/pom.xml
- maven_plugin/src/test/resources-its/it/IntegrationTestsIT/singleDependencyCheckMustWarn/src/main/java/HelloWorld.java
> introduce allowValidationFailure parameter

- .github/workflows/jreleaser.yml
- pom.xml
Another test, #992 did not work.
> 🛠️ export cyclonedx output to default folder

- README.md
- action.yml
- github_action/src/main/java/io/github/chains_project/maven_lockfile/GithubAction.java
- template/action.yml
> 👷 ci: Allow change of lockfile name in github action

- CHANGELOG.md
- action.yml
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.3.5 ff-merge

- CHANGELOG.md
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.4.0 ff-merge

- CHANGELOG.md
- action.yml
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.4.1 ff-merge

- CHANGELOG.md
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.4.2 ff-merge

- github_action/lockfile.json
- lockfile.json
- maven_plugin/lockfile.json
- pom.xml
> ➖ (deps): Remove maven-eclipse-plugin

- .github/workflows/jreleaser.yml
- .github/workflows/publish-action-artifact.yml
- pom.xml
See #1080 , #1161 , #1162 , and #1163 .
> 🚀 build (CD): Default to only sign sigstore during CD

- README.md
> :memo: New Banner image

- CHANGELOG.md
- action.yml
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.5.0 ff-merge

- github_action/pom.xml
- maven_plugin/pom.xml
- pom.xml
> :wrench: Specify view SCM url with tag of release

- CHANGELOG.md
- action.yml
- github_action/lockfile.json
- github_action/pom.xml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.5.1 ff-merge

- .github/workflows/ensure-notrunning-release.yml
- .github/workflows/ensure-release-notrunning.yml
> 👷 ci: Action to ensure relase is not running when merging PRs

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.5.2 ff-merge

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.5.3 ff-merge

- .github/actions/ghasum/action.yml
> 👷 ci: Remove ghasum binary after checksum verification

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.6.0 ff-merge

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.6.1 ff-merge

- .github/workflows/code-qualitiy.yml
- .github/workflows/codeql.yml
- .github/workflows/dependency-review.yml
- .github/workflows/doc.yml
- .github/workflows/gha.sum
- .github/workflows/ghasum.yml
- .github/workflows/jreleaser.yml
- .github/workflows/smoke-tests.yml
- renovate.json
> :pushpin: Pin GitHub actions

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.7.0 ff-merge

- CHANGELOG.md
- action.yml
- lockfile.json
- maven_plugin/lockfile.json
- maven_plugin/pom.xml
- pom.xml
> Release release/5.8.0 ff-merge
